POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
  "email": "ricardo1234@gmail.com",
  "password": "1234"
}

###

GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYTY2MGM5OS1hM2FiLTQyODYtODkwNi1jZGIyMWZhMTkxZjciLCJlbWFpbCI6InJpY2FyZG8xMjM0QGdtYWlsLmNvbSIsImlhdCI6MTc0ODkxMDE1MSwiZXhwIjoxNzQ4OTEwMTgxfQ.e1eHz0XXe4308e7wgRyFsllv4kPgN-_mJf5DZ-L7e3k

###

GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYTY2MGM5OS1hM2FiLTQyODYtODkwNi1jZGIyMWZhMTkxZjciLCJlbWFpbCI6InJpY2FyZG8xMjM0QGdtYWlsLmNvbSIsImlhdCI6MTc0ODkxMDg1NCwiZXhwIjoxNzQ4OTEwODg0fQ.--sHHfUwmzk2xQS_p63uSKdtR3GDANLf598sLmnpcI0